name: Update gist with WakaTime stats
# on:
#   schedule:
#     - cron: '*/10 * * * *'
on: [push, pull_request]
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 19af3d82679968115e9cbe78dec52232
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
